<?php

return [
    'status' => [
        '1' => 'Active',
        '0' => 'Inactive',
    ],
    'gender' => [
        '0' => 'Male',
        '1' => 'Female'
    ],
    'shortcoming_s' => [
        '0' => 'Dags för service (0-3 mån kvar)',
        '1' => 'Inte fullservad på verkstad enligt schema',
        '2' => 'Finns bara 1 bilnyckel',
        '3' => 'Finns sprickor eller stenskott i vindrutan',
        '4' => 'Sommardäcken är slitna och går troligtvis inte 1 säsong till',
        '5' => 'Vinterdäcken är slitna och går troligtvis inte 1 säsong till',
        '6' => 'Luktar tobaksrök i bilen',
        '7' => 'Finns tydliga spår av pälsdjur',
        '8' => 'Repor på lacken',
        '9' => 'Slitna däck',
        '10' => 'Motorlampa/varningslampa lyser',
        '11' => 'Dålig batteri vid start',
        '12' => 'Rost på bilen',
    ],
    'shortcoming_e' => [
        '0' => 'Time for service (0-3 months left)',
        '1' => 'Not fully serviced at the workshop according to schedule',
        '2' => 'There is only 1 car key',
        '3' => 'There are cracks or stone chips in the windshield',
        '4' => 'The summer tires are worn and probably will not last 1 more season',
        '5' => 'The winter tires are worn and will probably not last 1 more season',
        '6' => 'Smells like tobacco smoke in the car',
        '7' => 'There are clear traces of fur animals',
    ],
    'handover_s' => [
        '0' => 'Snarast',
        '1' => 'Inom en vecka',
    ],
    'handover_e' => [
        '0' => 'Anytime',
        '1' => 'In 1-2 weeks',
    ],
    'ordinary_s' => [
        '0' => 'Helskinn',
        '1' => 'Halvskinn eller alcantara',
        '2' => 'Dragkrok',
        '3' => 'Apple CarPlay / Android Auto',
        '4' => 'GPS - navigation (fungerande)',
        '5' => 'Bluetooth',
        '6' => 'Parkeringssensorer bak',
        '7' => 'Parkeringssensorer fram',
        '8' => 'Backkamera',
        '9' => 'Dieselvärmare (ej sladd)',
        '10' => 'Motorvärmare (sladd)',
        '11' => 'Taklucka eller panoramaglas',
        '12' => 'El stolar',
    ],
    'ordinary_e' => [
        'full_skin' => 'Full skin',
        'half_leather' => 'Half leather or alcantara',
        'towbar' => 'Towbar',
        'carplay' => 'Apple CarPlay / Android Auto',
        'gps' => 'GPS navigation (working)',
        'bluetooth' => 'Bluetooth',
        'rear_parking_sensor' => 'Rear parking sensors',
        'parking_sensor_front' => 'Parking sensors front',
        'rear_camera' => 'Rear view camera',
        'diesel_heater' => 'Diesel heater (not cord)',
        'engine_heater' => 'Engine heater (cord)',
        'sunroof' => 'Sunroof or panoramic glass',
        'El stolar' => 'El stolar'
    ],
    'wheel_s' => [
        '0' => 'Sommardäck med LM-fälg',
        '1' => 'Vinterdäck med LM-fälg',
        '2' => 'Åretruntdäck med LM-fälg',
        '3' => 'Sommardäck med plåtfälg',
        '4' => 'Vinterdäck med plåtfälg',
        '5' => 'Åretruntdäck med plåtfälg',
        '6' => 'Sommardäck endast gummi',
        '7' => 'Vinterdäck endast gummi',
        '8' => 'Åretruntdäck endast gummi',
    ],
    'wheel_e' => [
        '0' => 'Summer tires with LM rim',
        '1' => 'Winter tires with LM rim',
        '2' => 'Year-round tire with LM rim',
        '3' => 'Summer tires with sheet metal rims',
        '4' => 'Winter tires with sheet metal rims',
        '5' => 'Year-round tire with sheet metal rim',
        '6' => 'Summer tires only rubber',
        '7' => 'Winter tires only rubber',
        '8' => 'All-season tires rubber only',
    ],
    'place_s' => [
        '0' => 'Arvika',
        '1' => 'Borlänge',
    ],
    'place_e' => [
        '0' => 'Arvika',
        '1' => 'Borlänge',
    ],
    'lease_on_car' => [
        '0' => 'Ja',
        '1' => 'Nej',
    ],
];

